language: cpp
compiler:
  - gcc
before_install:
  - wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz -O SDL2-2.0.12.tar.gz
  - tar -xzvf SDL2-2.0.12.tar.gz
install:
  - (cd SDL2-2.0.12 && ./configure && make && sudo make install)
script: make
