/*
 * BG2AnimationFactory.h
 *
 *  Created on: 16/nov/2014
 *      Author: Stefano Ceccherini
 */

#ifndef BG2ANIMATIONFACTORY_H_
#define BG2ANIMATIONFACTORY_H_

#include "AnimationFactory.h"

// Multiple files
// Different files for different armor, gender, class, race
// Different files for different actions
// G1 = standing
// G11 = walking
// G15 = misc (dead, etc)
// An = attacking
// CA = casting
// Sn = ?

// Eastern orientations are generated by mirroring western orientations animations.

class BG2CharachterAnimationFactory: public AnimationFactory {
public:
	BG2CharachterAnimationFactory(const char* baseName, const uint16 id);
	~BG2CharachterAnimationFactory();

private:
	virtual animation_description GetAnimationDescription(Actor* actor);
	void _GetMirroredAnimation(int& orientation, animation_description& description);
};

#endif /* BG2ANIMATIONFACTORY_H_ */
