name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        submodules: recursive
    - name: sdl-get
      run: wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz -O SDL2-2.0.12.tar.gz
    - name: sdl-extract
      run: tar -xzvf SDL2-2.0.12.tar.gz
    - name: sdl-build
      run: (cd SDL2-2.0.12 && ./configure && make && sudo make install)
    - name: build-all
      run: make
